version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: '05:00'
    open-pull-requests-limit: 10
    target-branch: "development"
    commit-message:
      prefix: "build: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
